"""add villages table and farmer clerk_user_id

Revision ID: 6abc13fa7ddc
Revises: 8a468308b66a
Create Date: 2026-09-11 18:51:57.603966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abc13fa7ddc'
down_revision: Union[str, Sequence[str], None] = '8a468308b66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Single-village prototype: seed the row every farmer is auto-assigned to.
    op.execute("INSERT INTO villages (name) VALUES ('Rampur')")
    op.add_column('farmers', sa.Column('clerk_user_id', sa.String(length=191), nullable=False))
    op.add_column('farmers', sa.Column('village_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_farmers_clerk_user_id'), 'farmers', ['clerk_user_id'], unique=True)
    op.create_foreign_key(None, 'farmers', 'villages', ['village_id'], ['id'])
    op.drop_column('farmers', 'village')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('village', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'farmers', type_='foreignkey')
    op.drop_index(op.f('ix_farmers_clerk_user_id'), table_name='farmers')
    op.drop_column('farmers', 'village_id')
    op.drop_column('farmers', 'clerk_user_id')
    op.drop_table('villages')
    # ### end Alembic commands ###
