"""initial schema

Revision ID: 8a468308b66a
Revises: 
Create Date: 2026-09-11 17:55:55.772597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a468308b66a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.Enum('FARMER', 'JAL_VIGYANI', 'DAM_OPERATOR', 'SYSTEM', 'AI_AGENT', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_flow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('water_level', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('water_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('total_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_storage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inflow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('outflow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('measured_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INVESTIGATION_REQUIRED', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='anomalystatus'), nullable=False),
    sa.Column('possible_causes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conflict_code', sa.String(length=20), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'UNDER_REVIEW', 'NEGOTIATION', 'APPROVED', 'REVISION_REQUESTED', 'ESCALATED', 'RESOLVED', name='conflictstatus'), nullable=False),
    sa.Column('total_demand', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available_water', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shortage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conflict_code')
    )
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name='fk_farmers_field_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('flow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('water_level', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreement_code', sa.String(length=30), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=True),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'SUPERSEDED', 'CANCELLED', name='agreementstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('final_allocation', sa.JSON(), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['agreements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agreement_code')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('area_acres', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('crop', sa.String(length=80), nullable=False),
    sa.Column('crop_stage', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='notificationseverity'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('NEED_MORE_WATER', 'NEED_DIFFERENT_TIME', 'CROP_CRITICAL', 'EMERGENCY', 'OTHER', name='objectionreason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'REJECTED', name='objectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.String(length=20), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('crop', sa.String(length=80), nullable=False),
    sa.Column('urgency', sa.Enum('NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROPOSED', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocation_date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROPOSED', 'ACCEPTED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'MODIFIED', 'CANCELLED', 'DISPUTED', name='allocationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['water_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conflict_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['water_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conflict_id', 'farmer_id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivered_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_status', sa.Enum('ON_TRACK', 'COMPLETE', 'UNDER_DELIVERY', 'OVER_DELIVERY', 'INVESTIGATION_REQUIRED', name='deliverystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='schedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('deliveries')
    op.drop_table('conflict_participants')
    op.drop_table('allocations')
    op.drop_table('water_requests')
    op.drop_table('objections')
    op.drop_table('notifications')
    op.drop_table('fields')
    op.drop_table('agreements')
    op.drop_table('sensor_readings')
    op.drop_table('farmers')
    op.drop_table('conflicts')
    op.drop_table('anomalies')
    op.drop_table('water_sources')
    op.drop_table('canals')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
